# Generated by Django 5.2.4 on 2025-08-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
