# Generated by Django 5.2.4 on 2025-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumka',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
